# Generated by Django 4.2.11 on 2024-09-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories', models.FloatField()),
                ('carbohydrates', models.FloatField()),
                ('proteins', models.FloatField()),
                ('fats', models.FloatField()),
                ('fibers', models.FloatField()),
            ],
        ),
    ]
